import type { TierLevel } from './types';

export const INITIAL_TIME = 30;
export const DESCRAMBLE_COST = 25;

export const TIERS: Record<TierLevel, string[]> = {
    1: ['CAT', 'DOG', 'SUN', 'RUN', 'HAT', 'BAT', 'RAT', 'MAT', 'SAT', 'FAT'],
    2: ['BLUE', 'TREE', 'FIRE', 'WIND', 'RAIN', 'SNOW', 'MOON', 'STAR', 'BIRD', 'FISH'],
    3: ['HOUSE', 'WATER', 'LIGHT', 'NIGHT', 'PHONE', 'CLOUD', 'STORM', 'BEACH', 'RIVER', 'OCEAN'],
    4: ['BRIDGE', 'CASTLE', 'FOREST', 'DESERT', 'PLANET', 'ROCKET', 'SYSTEM', 'ENERGY', 'MATRIX', 'CIPHER'],
    5: ['QUANTUM', 'NETWORK', 'FIREWALL', 'PROTOCOL', 'DATABASE', 'TERMINAL', 'SECURITY', 'COMPILER', 'ALGORITHM', 'ENCRYPTION'],
    6: ['CRYPTOGRAPHY', 'VULNERABILITY', 'AUTHENTICATION', 'INFRASTRUCTURE', 'DECENTRALIZED', 'CYBERSECURITY', 'ARCHITECTURE', 'ORCHESTRATION', 'METAMORPHOSIS', 'SYNCHRONICITY']
};
